# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Peter Kettig
title: Development engineer
email: kettig.peter@gmail.com
# email_title: Email (Email title override)
# phone: +xx (0) xxx xxxxx
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username:petketrb
github_username: petket-5
# stackoverflow_username: "00000001"
# dribbble_username:petket
# facebook_username:petket
# flickr_username:petket
# instagram_username:petket
linkedin_username: https://www.linkedin.com/in/pkettig/
# xing_username:petket
# pinterest_username:petket
# youtube_username:petket
# googleplus_username: +jekyll
orcid_username: 0000-0001-5229-4889

# Additional icon links
# additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile_pic.png
about_content: | # this will include new lines to allow paragraphs
 Hi, my name is Peter Kettig, I'm an engineer passionate about space and astronautics. I have been working on developing computer-vision algorithms and full-scale spacecraft ground segments dedicated to earth observation for the past five years.
 My recent project brought me to monitor climate change and its impacts on earth using a variety of space-borne data within the framework of the [Space for Climate Observatory (SCO)](https://www.spaceclimateobservatory.org).

 I enjoy working in a highly technological field and building processing chains that help to better understand the underlying data - I have worked with a range of different languages and frameworks (including AI ones) and I am always looking for opportunities to work with something new.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SCO-FloodDAM
        link: spaceclimateobservatory.org/flooddam-garonne
        link_text: spaceclimateobservatory.org/flooddam
        quote: >
          Flood detection, assessment and monitoring from space
        description: | # this will include new lines to allow paragraphs
          I am lead of this Space for Climate Observatory (SCO) project that aims at detecting and monitoring flood events worldwide.
          The project is a joint collaboration of laboratories and industry partners, that leverages satellite, airborne and in-situ data of various types to combine them in ML-based processing blocks:
          - Optical-, IR- and SAR-Imagery
          - Altimetry
          - Gauge-station networks
          - Auxiliary data (Elevation models, climatology etc.)
      - layout: right
        title: MAJA
        link: github.com/cnes/maja
        # link_text: Project webpage
        quote: >
          Processing chain for atmospheric correction and cloud detection in multi-spectral imagery
        description: | # this will include new lines to allow paragraphs
          This computer-vision Level-2 processing chain runs i.a. on Sentinel-2 and Landsat-8 data to correct for atmospheric effects and to reliably detect clouds in each acquisition.
          At CNES, I am responsable for the development as well as the validation of updates to the algorithm and coordinating its integration into the respective data centers (such as [Theia](https://theia.cnes.fr)/[PEPS](https://peps.cnes.fr)).

          The outputs of MAJA pave the way for [WASP](https://gitlab.orfeo-toolbox.org/remote_modules/wasp), a Level-3 processing chain that creates cloud-free monthly syntheses which I am also responsable of.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Centre national d'études spatiales (CNES)
        sub_title: Development engineer
        caption: November 2017 - present
        link: cnes.fr
        # quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          I am currently working at CNES as an engineer for the department of earth observation. 
          I am managing the development of the Data Processing Unit (DPU) of the MicroCarb satellite, dedicated to monitoring CO2-emissions.
          Within the DPU, there are multiple processing levels that help to translate the raw data into usable scientific measurements and correct for artifacts in the acquisition chain, from Level-0 (raw, compressed CCSDS packets) to Level-3 (Global CO2 maps).
          
          As is common in space projects of this scale and space agencies in particular, I am coordinating multiple companies that each intervene with their own expertise to contribute building the ground segment.
          Organizing acceptance reviews for each new release and making sure the DPU is fully working, validated and integrated into the ground segment for launch are also part of my tasks here.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Luleå tekniska universitet, Luleå, Sweden
        sub_title: Double-degree Master of Science
        caption: 2015-2017
        quote: >
          Master of space science and technology
        description: | # this will include new lines to allow paragraphs
          This erasmus mundus master programme lead me to a double-degree and brought me to three different institutes and countries:
          - Julius-Maximilians Universität, chair of aerospace computer science in Würzburg, Germany:

            The focus in the first master semester was a team design project to build a suspended satellite mock-up, giving me more insight into how each subsystem interfaces with the rest as well as working together in a team.
          - Luleå tekniska universitet, Institute for space physics in Kiruna, Sweden:

            One semester of advanced courses on systems engineering for spacecraft and space physics. Given the location above the arctic circle, I also explored northern scandinavia as much as possible - Polar lights and Mid-summer night included.
          - Université Toulouse III Paul Sabatier, Institute for astrophysics in Toulouse, France:

            My final two semesters of the master, including my thesis (see below) and earning me a double-degree
      - layout: top-left
        title: Université Toulouse III Paul Sabatier, Toulouse, France
        sub_title: Master of Science
        caption: 2015-2017
        quote: >
          Master (M2) of space technique and instrumentation
        description: | # this will include new lines to allow paragraphs
          Specialisation and second year of the master programme with courses in instrumentation and robotics.
          A voluntary student project in which I participated took us to launch our own high-altitude balloon in southern France - I was in charge of creating the embedded system that would eventually create a temperature, pressure and humidity profile of the atmosphere.
          My final year thesis was being held at CNES in charge of benchmarking CV libraries for the Euclid science ground segment.
      - layout: top-right
        title: Julius-Maximilians Universität, Würzburg, Germany
        sub_title: Bachelor of Science
        caption: 2012-2015
        quote: >
          Bachelor in aerospace computer science
        description: | # this will include new lines to allow paragraphs
          During my time at JMU, I had courses on embedded systems for satellites, GNC as well as aeronautical engineering.
          I also worked as a lab assistant at the institute of aerospace computer science where I had my first contact with actual space systems: A ground station for meteorological-data in which I was tasked to detect anomalies in the received images.
          During this time, I also took part in teaching the first- and second-semester students, which was a valuable insight on how to get students excited about engineering and science.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not working, I enjoy my time outdoors during biking, hiking and climbing adventures in southern France.
      Football, surfing and snowboarding with friends are also regular activites depending on the season.
      Outside of sports activities, I am interested in photography, specifically astro-photography as well as more mecanical bits such as working on my bike and car in my free time.
      I am fluent (CEFR Level C1/C2) in three languages (english, french and german) and working steadily on my fourth (spanish)s.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
